chart-dirs:
  - ddb-proxy
  - foundryvtt
  - garage
  - home-assistant-matter-server
  - home-assistant-otbr
  - linkwarden
  - memos
  - node-red
  - paperless-ngx
  - yas3p
target-branch: master
use-helmignore: true
remote: origin
