---
# Source: home-assistant-matter-server/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: release-name-home-assistant-matter-server
  labels:
    helm.sh/chart: home-assistant-matter-server-0.1.0
    app.kubernetes.io/name: home-assistant-matter-server
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: "7.0.1"
    app.kubernetes.io/managed-by: Helm
automountServiceAccountToken: true
---
# Source: home-assistant-matter-server/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: release-name-home-assistant-matter-server
  labels:
    helm.sh/chart: home-assistant-matter-server-0.1.0
    app.kubernetes.io/name: home-assistant-matter-server
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: "7.0.1"
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: home-assistant-matter-server
    app.kubernetes.io/instance: release-name
---
# Source: home-assistant-matter-server/templates/statefulset.yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: release-name-home-assistant-matter-server
  labels:
    helm.sh/chart: home-assistant-matter-server-0.1.0
    app.kubernetes.io/name: home-assistant-matter-server
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: "7.0.1"
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  serviceName: release-name-home-assistant-matter-server
  selector:
    matchLabels:
      app.kubernetes.io/name: home-assistant-matter-server
      app.kubernetes.io/instance: release-name
  template:
    metadata:
      labels:
        helm.sh/chart: home-assistant-matter-server-0.1.0
        app.kubernetes.io/name: home-assistant-matter-server
        app.kubernetes.io/instance: release-name
        app.kubernetes.io/version: "7.0.1"
        app.kubernetes.io/managed-by: Helm
    spec:
      hostname: release-name-home-assistant-matter-server
      serviceAccountName: release-name-home-assistant-matter-server
      securityContext:
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
        runAsGroup: 1000
        runAsNonRoot: true
        runAsUser: 1000
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: home-assistant-matter-server
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - ALL
            privileged: false
            readOnlyRootFilesystem: true
            runAsGroup: 1000
            runAsNonRoot: true
            runAsUser: 1000
            seccompProfile:
              type: RuntimeDefault
          image: "ghcr.io/home-assistant-libs/python-matter-server:7.0.1"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 5580
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {}
          volumeMounts:
            - name: data
              mountPath: /data
            - name: tmp
              mountPath: /tmp
      volumes:
        - name: tmp
          emptyDir: {}
  volumeClaimTemplates:
    - metadata:
        name: data
        labels:
          app.kubernetes.io/name: home-assistant-matter-server
          app.kubernetes.io/instance: release-name
          app.kubernetes.io/managed-by: Helm
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 2Gi
---
# Source: home-assistant-matter-server/templates/tests/test-connection.yaml
apiVersion: v1
kind: Pod
metadata:
  name: "release-name-home-assistant-matter-server-test-connection"
  labels:
    helm.sh/chart: home-assistant-matter-server-0.1.0
    app.kubernetes.io/name: home-assistant-matter-server
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: "7.0.1"
    app.kubernetes.io/managed-by: Helm
  annotations:
    "helm.sh/hook": test
spec:
  containers:
    - name: wget
      image: busybox
      command: ['wget']
      args: ['release-name-home-assistant-matter-server:80']
  restartPolicy: Never
