apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "radicale.fullname" . }}
  labels:
    {{- include "radicale.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "radicale.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        {{- if .Values.config.create }}
        checksum/config: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
        {{- end }}
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "radicale.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "radicale.serviceAccountName" . }}
      automountServiceAccountToken: {{ .Values.serviceAccount.automount }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.registry }}/{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- with .Values.env }}
          env:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          ports:
            - name: http
              containerPort: {{ include "radicale.containerPort" . }}
              protocol: TCP
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: tmp
              mountPath: /tmp
            - name: data
              mountPath: {{ include "radicale.dataMountPath" . }}
            {{- if .Values.config.create }}
            - name: config
              mountPath: /etc/radicale
              readOnly: true
            {{- end }}
            {{- if and .Values.config.create (eq .Values.config.auth.type "htpasswd") }}
            - name: auth
              mountPath: {{ dir (include "radicale.authFilePath" .) }}
              readOnly: true
            {{- end }}
            {{- if and .Values.config.create (eq .Values.config.rights.type "from_file") }}
            - name: rights
              mountPath: {{ dir (include "radicale.rightsFilePath" .) }}
              readOnly: true
            {{- end }}
          {{- with .Values.volumeMounts }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
      volumes:
        - name: tmp
          emptyDir: {}
        - name: data
        {{- if .Values.persistence.data.enabled }}
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.data.existingVolumeClaim | default (include "radicale.dataPvcName" .) }}
        {{- else }}
          emptyDir: {}
        {{- end }}
        {{- if .Values.config.create }}
        - name: config
          secret:
            secretName: {{ include "radicale.configSecretName" . }}
            items:
              - key: config
                path: config
        {{- end }}
        {{- if and .Values.config.create (eq .Values.config.auth.type "htpasswd") }}
        - name: auth
          secret:
            {{- if .Values.config.auth.htpasswd.existingSecret }}
            secretName: {{ .Values.config.auth.htpasswd.existingSecret }}
            items:
              - key: {{ .Values.config.auth.htpasswd.existingSecretKey }}
                path: {{ base (include "radicale.authFilePath" .) }}
            {{- else }}
            secretName: {{ include "radicale.configSecretName" . }}
            items:
              - key: htpasswd
                path: {{ base (include "radicale.authFilePath" .) }}
            {{- end }}
        {{- end }}
        {{- if and .Values.config.create (eq .Values.config.rights.type "from_file") }}
        - name: rights
          secret:
            {{- if .Values.config.rights.file.existingSecret }}
            secretName: {{ .Values.config.rights.file.existingSecret }}
            items:
              - key: {{ .Values.config.rights.file.existingSecretKey }}
                path: {{ base (include "radicale.rightsFilePath" .) }}
            {{- else }}
            secretName: {{ include "radicale.configSecretName" . }}
            items:
              - key: rights
                path: {{ base (include "radicale.rightsFilePath" .) }}
            {{- end }}
        {{- end }}
      {{- with .Values.volumes }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
