{{- if and .Values.persistence.data.enabled (not .Values.persistence.data.existingVolumeClaim) }}
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ include "radicale.dataPvcName" . }}
  labels:
    {{- include "radicale.labels" . | nindent 4 }}
spec:
  {{- if .Values.persistence.data.className }}
  storageClassName: {{ .Values.persistence.data.className | quote }}
  {{- end }}
  accessModes:
    - {{ .Values.persistence.data.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.persistence.data.size | quote }}
{{- end }}
