{{- if and .Values.config.create (not .Values.config.existingSecret) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "radicale.configSecretName" . }}
  labels:
    {{- include "radicale.labels" . | nindent 4 }}
type: Opaque
stringData:
  config: |
    {{- .Values.config.content | nindent 4 }}
{{- end }}
