{{- if .Values.config.create -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "radicale.configSecretName" . }}
  labels:
    {{- include "radicale.labels" . | nindent 4 }}
type: Opaque
stringData:
  config: |
    {{- include "radicale.configContent" . | trim | nindent 4 }}
  {{- if and (eq .Values.config.auth.type "htpasswd") .Values.config.auth.htpasswd.users (not .Values.config.auth.htpasswd.existingSecret) }}
  htpasswd: |
    {{- include "radicale.htpasswdContent" . | trim | nindent 4 }}
  {{- end }}
  {{- if and (eq .Values.config.rights.type "from_file") .Values.config.rights.file.content (not .Values.config.rights.file.existingSecret) }}
  rights: |
    {{- .Values.config.rights.file.content | trim | nindent 4 }}
  {{- end }}
{{- end }}
