apiVersion: v2
name: filebrowser
description: |
  A Helm chart for filebrowser.
  File Browser provides a file managing interface within a specified directory and it can be used to upload, delete, preview and edit your files.
  It is a create-your-own-cloud-kind of software where you can just install it on your server, direct it to a path and access your files through a nice web interface.
type: application
version: 0.1.0
appVersion: "v2.63.16" # renovate: datasource=docker depName=filebrowser/filebrowser versioning=docker
sources:
  - https://github.com/wittdennis/charts/tree/main/filebrowser
  - https://github.com/filebrowser/filebrowser
icon: https://raw.githubusercontent.com/wittdennis/charts/refs/heads/main/filebrowser/assets/icon.png
keywords:
  - file explorer
  - explorer
  - file management
  - file browser
