apiVersion: v2
name: radicale
description: |
  A Helm chart for Radicale.
  Radicale is a small but powerful CalDAV (calendars, to-do lists) and CardDAV (contacts) server.
  This chart uses the official, rootless ghcr.io/kozea/radicale image.
type: application
version: 2.0.2
appVersion: "3.7.7" # renovate: datasource=docker depName=ghcr.io/kozea/radicale
sources:
  - https://github.com/wittdennis/charts/tree/main/radicale
  - https://github.com/Kozea/Radicale
icon: https://raw.githubusercontent.com/wittdennis/charts/refs/heads/main/radicale/assets/icon.svg
keywords:
  - radicale
  - caldav
  - carddav
  - calendar
  - contacts
