apiVersion: v2
name: linkwarden
description: |
  Linkwarden is a self-hosted, open-source collaborative bookmark manager to collect, read, annotate, and fully preserve what matters, all in one place.
type: application
version: 1.1.2
appVersion: "v2.16.2" # renovate: datasource=docker depName=ghcr.io/linkwarden/linkwarden versioning=semver
sources:
  - https://github.com/wittdennis/charts/tree/main/linkwarden
icon: https://raw.githubusercontent.com/wittdennis/charts/refs/heads/main/linkwarden/assets/icon.png
keywords:
  - bookmarks
  - archival
annotations:
  org.opencontainers.image.source: https://github.com/wittdennis/charts
  org.opencontainers.image.licenses: MIT
  org.opencontainers.image.documentation: https://github.com/wittdennis/charts/tree/main/linkwarden
  artifacthub.io/license: MIT
  artifacthub.io/images: |
    - name: linkwarden
      image: ghcr.io/linkwarden/linkwarden:v2.16.2 # renovate
maintainers:
  - name: Dennis Witt
    url: https://github.com/wittdennis
