apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "otbr.fullname" . }}
  labels:
    {{- include "otbr.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "otbr.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "otbr.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      hostname: {{ include "otbr.fullname" . }}
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      automountServiceAccountToken: {{ .Values.serviceAccount.automount }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "otbr.serviceAccountName" . }}
      securityContext:
        runAsUser: 0
        runAsGroup: 0
        runAsNonRoot: false
        # sysctls:
        #   - name: net.ipv6.conf.all.disable_ipv6
        #     value: "0"
        #   - name: net.ipv4.conf.all.forwarding
        #     value: "1"
        #   - name: net.ipv6.conf.all.forwarding
        #     value: "1"
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            runAsNonRoot: false
            runAsUser: 0
            runAsGroup: 0
            privileged: true
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: HTTP_PORT
              value: "8888"
          args:
            - --radio-url
            - spinel+hdlc+uart://{{ .Values.rcpMountPath }}
            - --backbone-interface {{ .Values.backboneInterface }}
          ports:
            - name: http
              containerPort: 8888
              protocol: TCP
          {{- with .Values.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: rcp
              mountPath: {{ .Values.rcpMountPath }}
          {{- with .Values.volumeMounts }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
      volumes:
        - name: rcp
          hostPath:
            path: {{ .Values.rcpMountPath }}
      {{- with .Values.volumes }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
