apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "paperless-ngx.fullname" . }}
  labels:
    {{- include "paperless-ngx.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "paperless-ngx.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "paperless-ngx.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "paperless-ngx.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.registry }}/{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          env:
            - name: PAPERLESS_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  key: key
                  name: {{ include "paperless-ngx.secretKeyName" . }}
            - name: USERMAP_UID
              value: {{ .Values.securityContext.runAsUser | quote }}
            - name: USERMAP_GID
              value: {{ .Values.securityContext.runAsGroup | quote }}
            {{- if .Values.securityContext.readOnlyRootFilesystem }}
            - name: PAPERLESS_SUPERVISORD_WORKING_DIR
              value: /tmp
            - name: PYTHONPYCACHEPREFIX
              value: /tmp/pycache
            - name: S6_READ_ONLY_ROOT
              value: "1"
            {{- end }}
            {{- if .Values.route.enabled }}
            {{- with (first .Values.route.hostnames) }}
            - name: PAPERLESS_URL
              value: https://{{ . }}
            {{- end }}
            {{- else if .Values.ingress.enabled }}
            {{- with (first .Values.ingress.hosts) }}
            - name: PAPERLESS_URL
              value: https://{{ .host }}
            {{- end }}
            {{- end }}
            {{- if .Values.redis.prefix }}
            - name: PAPERLESS_REDIS_PREFIX
              value: {{ .Values.redis.prefix }}
            {{- end}}
            - name: PAPERLESS_REDIS
            {{- if .Values.redis.connectionSecret.name }}
              valueFrom:
                secretKeyRef:
                  key: {{ .Values.redis.connectionSecret.key }}
                  name: {{ .Values.redis.connectionSecret.name }}
            {{- else}}
              value: {{ .Values.redis.connectionUrl }}
            {{- end }}
            {{- if not (eq .Values.database.engine "sqlite") }}
            - name: PAPERLESS_DBENGINE
              value: {{ .Values.database.engine }}
            - name: PAPERLESS_DBHOST
              value: {{ .Values.database.host }}
            {{- if .Values.database.port }}
            - name: PAPERLESS_DBPORT
              value: {{ .Values.database.port | quote }}
            {{- end}}
            {{- if .Values.database.databaseName }}
            - name: PAPERLESS_DBNAME
              value: {{ .Values.database.databaseName }}
            {{- end }}
            - name: PAPERLESS_DBUSER
            {{- if .Values.database.userSecret.name }}
              valueFrom:
                secretKeyRef:
                  key: {{ .Values.database.userSecret.key }}
                  name: {{ .Values.database.userSecret.name }}
            {{- else }}
              value: {{ .Values.database.user }}
            {{- end }}
            - name: PAPERLESS_DBPASS
            {{- if .Values.database.passwordSecret.name }}
              valueFrom:
                secretKeyRef:
                  key: {{ .Values.database.passwordSecret.key }}
                  name: {{ .Values.database.passwordSecret.name }}
            {{- else }}
              value: {{ .Values.database.password }}
            {{- end }}
            {{- end}}
            - name: PAPERLESS_DB_READ_CACHE_ENABLED
              value: {{ .Values.database.enableReadCache | quote }}
            - name: PAPERLESS_READ_CACHE_TTL
              value: {{ printf "%d" (.Values.database.readCacheTTL | int64) | quote }}
            - name: PAPERLESS_ACCOUNT_ALLOW_SIGNUPS
              value: {{ .Values.auth.allowSignup | quote }}
            - name: PAPERLESS_ACCOUNT_DEFAULT_GROUPS
              value: {{ .Values.auth.defaultGroups | quote }}
            - name: PAPERLESS_SESSION_COOKIE_AGE
              value: {{ printf "%d" (.Values.auth.cookieAge | int64) | quote }}
            - name: PAPERLESS_ACCOUNT_SESSION_REMEMBER
              value: {{ .Values.auth.rememberSession | quote }}
            {{- if .Values.auth.sso.providersSecret.name }}
            - name: PAPERLESS_SOCIALACCOUNT_PROVIDERS
              valueFrom:
                secretKeyRef:
                  key: {{ .Values.auth.sso.providersSecret.key }}
                  name: {{ .Values.auth.sso.providersSecret.name }}
            {{- end }}
            {{- if .Values.tweaks.apps }}
            - name: PAPERLESS_APPS
              value: {{ .Values.tweaks.apps | quote }}
            {{- end }}
            - name: PAPERLESS_SOCIAL_AUTO_SIGNUP
              value: {{ .Values.auth.sso.autoSignup | quote }}
            - name: PAPERLESS_SOCIALACCOUNT_ALLOW_SIGNUPS
              value: {{ .Values.auth.sso.allowSignup | quote }}
            - name: PAPERLESS_SOCIAL_ACCOUNT_SYNC_GROUPS
              value: {{ .Values.auth.sso.syncGroups | quote }}
            {{- if .Values.auth.sso.defaultGroups }}
            - name: PAPERLESS_SOCIAL_ACCOUNT_DEFAULT_GROUPS
              value: {{ .Values.auth.sso.defaultGroups | quote }}
            {{- end }}
            - name: PAPERLESS_DISABLE_REGULAR_LOGIN
              value: {{ .Values.auth.sso.disableRegularLogin | quote }}
            - name: PAPERLESS_REDIRECT_LOGIN_TO_SSO
              value: {{ .Values.auth.sso.autoRedirect | quote }}
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - mountPath: /tmp
              name: tmp
            {{- if .Values.securityContext.readOnlyRootFilesystem }}
            - mountPath: /run
              name: run
            {{- end }}
            - name: paperless-ngx-data
              mountPath: /usr/src/paperless/data
            - name: paperless-ngx-media
              mountPath: /usr/src/paperless/media
            - name: paperless-ngx-export
              mountPath: /usr/src/paperless/export
            - name: paperless-ngx-consume
              mountPath: /usr/src/paperless/consume
          {{- with .Values.volumeMounts }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
      volumes:
        - name: tmp
          emptyDir: {}
        {{- if .Values.securityContext.readOnlyRootFilesystem }}
        - name: run
          emptyDir:
            medium: Memory
        {{- end }}
        - name: paperless-ngx-data
        {{- if .Values.persistence.data.enabled }}
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.data.existingVolumeClaim | default (include "paperless-ngx.dataPvcName" .) }}
        {{- else }}
          emptyDir: {}
        {{- end }}
        - name: paperless-ngx-media
        {{- if .Values.persistence.media.enabled }}
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.media.existingVolumeClaim | default (include "paperless-ngx.mediaPvcName" .) }}
        {{- else }}
          emptyDir: {}
        {{- end }}
        - name: paperless-ngx-export
        {{- if .Values.persistence.export.enabled }}
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.export.existingVolumeClaim | default (include "paperless-ngx.exportPvcName" .) }}
        {{- else }}
          emptyDir: {}
        {{- end }}
        - name: paperless-ngx-consume
        {{- if .Values.persistence.consume.enabled }}
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.consume.existingVolumeClaim | default (include "paperless-ngx.consumePvcName" .) }}
        {{- else }}
          emptyDir: {}
        {{- end }}
      {{- with .Values.volumes }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
