{{- if and .Values.persistence.data.enabled  (not .Values.persistence.data.existingVolumeClaim) }}
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ include "paperless-ngx.dataPvcName" . }}
  labels:
    {{- include "paperless-ngx.labels" . | nindent 4 }}
spec:
  {{- if .Values.persistence.data.storageClass }}
  storageClassName: {{ .Values.persistence.data.storageClass | quote }}
  {{- end }}
  accessModes:
    - {{ .Values.persistence.data.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.persistence.data.size | quote }}
{{- end }}
