{{- if .Values.hosting.secretKey.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "paperless-ngx.secretKeyName" . }}
  labels:
    {{- include "paperless-ngx.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if (lookup "v1" "Secret" .Release.Namespace (include "paperless-ngx.secretKeyName" .)).data }}
  key: (lookup "v1" "Secret" .Release.Namespace (include "paperless-ngx.secretKeyName" .)).data
  {{- else }}
  key: {{ randAlphaNum 64 | b64enc | quote }}
  {{- end }}
{{- end }}
