apiVersion: v2
name: memos
description: A Helm chart for memos (https://usememos.com)
type: application
version: 1.0.0
appVersion: "0.26.1" # renovate: datasource=docker depName=neosmemo/memos versioning=docker
sources:
  - https://github.com/wittdennis/charts/tree/master/memos
icon: https://raw.githubusercontent.com/wittdennis/charts/refs/heads/master/memos/assets/icon.png
keywords:
  - notes
  - keep
  - memos
  - journal
