apiVersion: v2
name: garage
description: S3-compatible object store for small self-hosted geo-distributed deployments.
type: application
version: 1.1.0
appVersion: "v2.1.0" # renovate: datasource=docker depName=dxflrs/amd64_garage versioning=docker
home: https://garagehq.deuxfleurs.fr/
icon: https://garagehq.deuxfleurs.fr/images/garage-logo.svg
keywords:
  - geo-distributed
  - read-after-write-consistency
  - s3-compatible
sources:
  - https://git.deuxfleurs.fr/Deuxfleurs/garage.git
  - https://github.com/wittdennis/charts/tree/master/garage
maintainers: []
