{{- if .Values.route.enabled -}}
{{- $fullName := include "node-red.fullname" . -}}
{{- $svcPort := .Values.service.port -}}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "node-red.labels" . | nindent 4 }}
    {{- with .Values.route.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.route.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- with .Values.route.hostnames }}
  hostnames:
    {{- tpl (toYaml .) $ | nindent 4 }}
  {{- end }}
  {{- with .Values.route.parentRefs }}
  parentRefs:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  rules:
    {{- if .Values.route.additionalRules }}
    {{- tpl (toYaml .Values.route.additionalRules) $ | nindent 4 }}
    {{- end }}
    - backendRefs:
        - name: {{ $fullName }}
          port: {{ $svcPort }}
          weight: 100
      {{- with .Values.route.matches }}
      matches:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.route.filters }}
        {{- toYaml . | nindent 8 }}
      {{- end -}}
{{- end }}
