apiVersion: apps/v1
kind: {{ .Values.deployment.kind }}
metadata:
  name: {{ include "linkwarden.fullname" . }}
  labels:
    {{- include "linkwarden.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "linkwarden.selectorLabels" . | nindent 6 }}
  {{- if eq .Values.deployment.kind "StatefulSet" }}
  serviceName: {{ include "linkwarden.fullname" . }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        {{- with .Values.podAnnotations }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "linkwarden.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      automountServiceAccountToken: {{ .Values.serviceAccount.automount }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "linkwarden.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.registry }}/{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: {{ required "Postgres existing secret is required" .Values.linkwarden.postgres.existingSecret }}
                  key: uri
            - name: NEXTAUTH_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ required "Existing secret for authSecret is required" .Values.linkwarden.authSecret.existingSecret }}
                  key: auth-secret
            {{- if .Values.linkwarden.meilisearch.host }}
            - name: MEILI_MASTER_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ required "Existing secret for meilisearch is required" .Values.linkwarden.meilisearch.existingSecret }}
                  key: master-key
            {{- end}}
          envFrom:
            - configMapRef:
                name: {{ include "linkwarden.fullname" . }}
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          {{- with .Values.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: tmp
              mountPath: /tmp
            - name: next-cache
              mountPath: /data/apps/web/.next/cache
            - name: data
              mountPath: /data/data
            {{- with .Values.volumeMounts }}
              {{- toYaml . | nindent 12 }}
            {{- end }}
      volumes:
        - name: tmp
          emptyDir: {}
        - name: next-cache
          emptyDir: {}
        {{- if and .Values.persistence.enabled }}
        {{- if eq .Values.deployment.kind "DaemonSet" }}
        - name: data
          hostPath:
            path: {{ .Values.persistence.hostPath }}
            type: DirectoryOrCreate
        {{- end }}
        {{- else }}
        - name: meta
          emptyDir: {}
        - name: data
          emptyDir: {}
        {{- end }}
        {{- with .Values.volumes }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
  {{- if and .Values.persistence.enabled (eq .Values.deployment.kind "StatefulSet") }}
  volumeClaimTemplates:
    - apiVersion: v1
      metadata:
        name: data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        {{- with .Values.persistence.storageClass }}
        storageClassName: {{ . | quote }}
        {{- end }}
        resources:
          requests:
            storage: {{ .Values.persistence.size | quote }}
  {{- end }}
